ALTER TABLE TB_USER ADD (
    CONT_SITE_CD CHAR(2)
);

ALTER TABLE TB_USER ADD (
    AGREE1_YN CHAR(1)
);

ALTER TABLE TB_USER ADD (
    AGREE2_YN CHAR(1)
);

ALTER TABLE TB_USER MODIFY (
    USER_ID VARCHAR(50)
);