/*
INSERT INTO TB_COMM_CODE (
    GRP_CD, DITC_CD, DITC_NM, DITC_NM_ENG, VALUE_CD, VALUE_CD2, CD_EXP, CD_EXP_ENG,
    V_ORDER, LOCK_YN, USE_YN, REG_ID, REG_DTTM, UPD_ID, UPD_DTTM
) VALUES (
    'B1009', 'IDEA01', '데이터 개방', 'Data Open', NULL, NULL, NULL, NULL,
    1, 'N', 'Y', NULL, SYSDATE, NULL, NULL
);
INSERT INTO TB_COMM_CODE (
    GRP_CD, DITC_CD, DITC_NM, DITC_NM_ENG, VALUE_CD, VALUE_CD2, CD_EXP, CD_EXP_ENG,
    V_ORDER, LOCK_YN, USE_YN, REG_ID, REG_DTTM, UPD_ID, UPD_DTTM
) VALUES (
    'B1009', 'IDEA02', '사이트 개설 요청', 'Site Open Request', NULL, NULL, NULL, NULL,
    1, 'N', 'Y', NULL, SYSDATE, NULL, NULL
);
INSERT INTO TB_COMM_CODE (
    GRP_CD, DITC_CD, DITC_NM, DITC_NM_ENG, VALUE_CD, VALUE_CD2, CD_EXP, CD_EXP_ENG,
    V_ORDER, LOCK_YN, USE_YN, REG_ID, REG_DTTM, UPD_ID, UPD_DTTM
) VALUES (
    'B1009', 'IDEA03', '자유제안', 'Open Suggest', NULL, NULL, NULL, NULL,
    1, 'N', 'Y', NULL, SYSDATE, NULL, NULL
);
*/

/*
INSERT INTO TB_COMM_CODE (
    GRP_CD, DITC_CD, DITC_NM, DITC_NM_ENG, VALUE_CD, VALUE_CD2, CD_EXP, CD_EXP_ENG,
    V_ORDER, LOCK_YN, USE_YN, REG_ID, REG_DTTM, UPD_ID, UPD_DTTM
) VALUES (
    'B1010', 'DEVELOP01', '데이터 개방', 'Data Open', NULL, NULL, NULL, NULL,
    1, 'N', 'Y', NULL, SYSDATE, NULL, NULL
);
INSERT INTO TB_COMM_CODE (
    GRP_CD, DITC_CD, DITC_NM, DITC_NM_ENG, VALUE_CD, VALUE_CD2, CD_EXP, CD_EXP_ENG,
    V_ORDER, LOCK_YN, USE_YN, REG_ID, REG_DTTM, UPD_ID, UPD_DTTM
) VALUES (
    'B1010', 'DEVELOP02', '사이트 개설 요청', 'Site Open Request', NULL, NULL, NULL, NULL,
    1, 'N', 'Y', NULL, SYSDATE, NULL, NULL
);
INSERT INTO TB_COMM_CODE (
    GRP_CD, DITC_CD, DITC_NM, DITC_NM_ENG, VALUE_CD, VALUE_CD2, CD_EXP, CD_EXP_ENG,
    V_ORDER, LOCK_YN, USE_YN, REG_ID, REG_DTTM, UPD_ID, UPD_DTTM
) VALUES (
    'B1010', 'DEVELOP03', '자유제안', 'Open Suggest', NULL, NULL, NULL, NULL,
    1, 'N', 'Y', NULL, SYSDATE, NULL, NULL
);
*/

/*
INSERT INTO TB_COMM_CODE (
    GRP_CD, DITC_CD, DITC_NM, DITC_NM_ENG, VALUE_CD, VALUE_CD2, CD_EXP, CD_EXP_ENG,
    V_ORDER, LOCK_YN, USE_YN, REG_ID, REG_DTTM, UPD_ID, UPD_DTTM
) VALUES (
    'B1011', 'DATA01', '데이터 개방', 'Data Open', NULL, NULL, NULL, NULL,
    1, 'N', 'Y', NULL, SYSDATE, NULL, NULL
);
INSERT INTO TB_COMM_CODE (
    GRP_CD, DITC_CD, DITC_NM, DITC_NM_ENG, VALUE_CD, VALUE_CD2, CD_EXP, CD_EXP_ENG,
    V_ORDER, LOCK_YN, USE_YN, REG_ID, REG_DTTM, UPD_ID, UPD_DTTM
) VALUES (
    'B1011', 'DATA02', '사이트 개설 요청', 'Site Open Request', NULL, NULL, NULL, NULL,
    1, 'N', 'Y', NULL, SYSDATE, NULL, NULL
);
INSERT INTO TB_COMM_CODE (
    GRP_CD, DITC_CD, DITC_NM, DITC_NM_ENG, VALUE_CD, VALUE_CD2, CD_EXP, CD_EXP_ENG,
    V_ORDER, LOCK_YN, USE_YN, REG_ID, REG_DTTM, UPD_ID, UPD_DTTM
) VALUES (
    'B1011', 'DATA03', '자유제안', 'Open Suggest', NULL, NULL, NULL, NULL,
    1, 'N', 'Y', NULL, SYSDATE, NULL, NULL
);
*/